### ISSUE TITLE
Send Raven Assets

### ISSUE THREAD

**Issue by lastmeta** [moontreeapp/raven_back#31]
**Is your feature request related to a problem? Please describe.**
Users should be able to send Raven Assets.

**Describe the solution you'd like**
We can send RVN by making a transaction, RVN asset sending transactions should also be supported by ravencoin_wallet

**Task:**
- [ ] https://github.com/moontreeapp/raven_back/issues/2
- [ ] https://github.com/moontreeapp/raven_back/issues/6
- [x] https://github.com/moontreeapp/raven_back/issues/32
- [x] https://github.com/moontreeapp/raven_front/issues/26
